export const constants = {
    SET_RANDOM_NEWS_ITEMS: 'SET_RANDOM_NEWS_ITEMS',
    SET_RANDOM_NEWS_CHOSEN_ITEM: 'SET_RANDOM_NEWS_CHOSEN_ITEM',
    SET_RANDOM_NEWS_CHOSEN_IMAGE: 'SET_RANDOM_NEWS_CHOSEN_IMAGE',
}