export const constants = {
    SET_CATEGORIES_INFO: 'SET_CATEGORIES_INFO',
    SET_CHOSEN_CATEGORY_NAME: 'SET_CHOSEN_CATEGORY_NAME',
    SET_CHOSEN_CATEGORY_ITEMS: 'SET_CHOSEN_CATEGORY_ITEMS',
    SET_IS_SEARCH: 'SET_IS_SEARCH',
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
}