export const constants = {
    SET_CATEGORIES_INFO: 'SET_CATEGORIES_INFO',
    SET_CHOSEN_CATEGORY_NAME: 'SET_CHOSEN_CATEGORY_NAME',
    SET_CHOSEN_CATEGORY_ITEMS: 'SET_CHOSEN_CATEGORY_ITEMS',
    SET_IS_SEARCH: 'SET_IS_SEARCH',
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_CHOSEN_CATEGORY_ITEMS_EMPTY: 'SET_CHOSEN_CATEGORY_ITEMS_EMPTY',
    SET_NEXT_PAGE_URLS: 'SET_NEXT_PAGE_URLS',
    SET_NEXT_PAGE_URLS_EMPTY: 'SET_NEXT_PAGE_URLS_EMPTY',
    SET_PAGE_COUNT: 'SET_PAGE_COUNT',
}