export const constants = {
    SET_ITEM_TO_FAVOURITES: 'SET_ITEM_TO_FAVOURITES',
    SET_ITEM_REMOVE_FROM_FAVOURITES: 'SET_ITEM_REMOVE_FROM_FAVOURITES',
    SET_FAVOURITES_EMPTY: 'SET_FAVOURITES_EMPTY',
}